### ISSUE TITLE
Dock icons spread beyond scop of panel

### ISSUE THREAD

**Issue by aptanet** [robint99/mate-dock-applet#108]
Applications added disappear of the top and bottom of the applet when added. I have added the icons by dragging them from the Brisk Menu. Initially they appear at the bottom of the list rather than where they are placed, but they can be dragged up into position. When more are added they make the list bigger, but there is no way to scroll through them or slide them up and down to access those that are at the top and bottom of the list. The top ones vanish behind the Brisk Menu. In the attached screenshot I have Firefox at the top partly obscured by the Brisk Menu and one or two extra applications below Quassel that is partly off the bottom of the dock. Presumably the workspaces and trash are down there too!

This install has been upgraded from a clean install of Ubuntu MATE 17.04 that was patched up to date and then upgraded to the Ubuntu MATE 17.10 beta.

![dock-bug](https://user-images.githubusercontent.com/6049698/30004864-62c6b9e8-90ce-11e7-932a-ab6b3178b704.png)

**Comment by szabiakanich** [comment]
Tested it as well on Ubuntu Mate 17.10 Beta 1 and I have the same issue as described above.

In addition to that I'm facing a few more issues:
- when I add a new Icon from the Brisk menu it always adds it to the bottom of the stack and when I try to move the icond around it gets duplicated
- sometimes the brisk menu icon starts to blink randomly

**Comment by gsantner** [comment]
This seems to be the biggest problem of this application so far. I usually work with a lot of applications, and if I cant reach other applications that are open this is not ready for use. Tried it on ubuntu mate beta1 and opened many applications. There is absolutely no way to reach the bottom items. Neither scrolling nor anything else.

Thanks for working on this applet!


![screenshot at 2017-09-25 09-18-28](https://user-images.githubusercontent.com/6735650/30801315-312a24bc-a1e3-11e7-864c-d0b52476add5.png)

**Comment by aptanet** [comment]
Looks to be the same, I lose the Brisk menu off the top and the waste basket off the bottom (along with the workspace switcher) and the applications follow on from that, spreading off the top and bottom as I start more applications.

I also find, mainly with Firefox now, that the icon never stops blinking. Initially I had it with Caja and a couple of other applications, but now it is pretty much purely Firefox. I think that is down to the fact that I end up with a second dock icon for the running Firefox, so presumably the process isn't matched once it has started. If I pin the running Firefox it starts quite happily from there, but you lose the right click options for New Window and New Private Window unless you manually edit the .desktop file. What I have noticed is that the .desktop file of the default one simply has:

Exec=firefox -new-window

Whereas the working pinned one (in my home directory) has:

Exec=/usr/bin/firefox

I've not yet tried modifying the default one (or checking which package it comes in with, it may not be an option to modify the .desktop file if it isn't causing an issue for other desktops/docks).

I'm also having regular crashes with the mate-dock-applet python script. It shows promise, but on my machine I'm only really sticking with it to provide feedback to help it improve.

**Comment by gsantner** [comment]
I would put the blinking in a seperate issue and remove the stuff about it from this one

**Comment by aptanet** [comment]
Good point. I've actually got a selection of bug reports on Launchpad, but nothing seems to be happening with them there. I may copy them across to here.

**Comment by gsantner** [comment]
I didn't try/use Mate for quite some time and tried the latest version of mate and this applet today. I only can tell that this is not fixed yet (if somebody is looking for this info). 

![bildschirmfoto vom 2018-01-12 22-25-39](https://user-images.githubusercontent.com/6735650/34895907-f69994b2-f7e7-11e7-8932-338b2eba75e7.png)

**Comment by robint99** [comment]
Closed as very old issue. Also, this was fixed with the release of V0.81.
