### ISSUE TITLE
NOTHING!

### ISSUE THREAD

**Issue by caltrop-3** [robint99/mate-dock-applet#109]
can not get it to do anything

installed, re-booted... NOTHING!

 CPU - AMD Athlon(tm) II P360 Dual-Core x 2
MEM - 3783MB (1009MB used)
SCSI - ATA WDC WD3200BEVT-7 320 GB
           TSSTcorp DVD+-RW TS-L633C
   OS - Linux Mint 18.2 Sonya
           Kernal Linux 4.10.0-33-generic x86_64
           MATE 1.18.0

**Comment by darkshram** [comment]
Recently I made packages for my Linux distro and figured out the full dependencies list. You need to have installed all this python3 modules:

- cairo
- gobject
- pillow
- pyxdg
- scipy
- xlib

In a Fedora-like distro these are the dependency packages: libwnck3, keybinder3, python3-cairo, python3-gobject, python3-pillow, python3-pyxdg, python3-scipy and python3-xlib. Guess you will have to install the Linux Mint equivalents.

**Comment by iwantedsupernovabutitwastaken** [comment]
@darkshram  Sorry for bumping an old thread but i installed it all (your dependency list) but it still doesn't work. Arch+mate here.

**Comment by oz123** [comment]
You also need bamf from here https://launchpad.net/bamf

**Comment by robint99** [comment]
Closed due to age and also related to #118.
