### ISSUE TITLE
No way to reach items when much different applications are open

### ISSUE THREAD

**Issue by gsantner** [robint99/mate-dock-applet#110]
I opened many applications and found out that there is no way to scroll to the other items, or reach them by any other way than alt-tabbing. The system is ubuntu mate 17.10 beta1

This can be resolved by
* Making the list scrollable
* Shrinking icons so all do fit in height

Dash-to-Dock support both, but I think scrollable list alone is enough.

Thanks for working on this applet!

![screenshot at 2017-09-25 09-18-28](https://user-images.githubusercontent.com/6735650/30823539-c6863228-a22c-11e7-98cc-7ff89dff9c24.png)

**Comment by flexiondotorg** [comment]
This looks like a duplicate of #108

**Comment by gsantner** [comment]
I put it in a seperate issue because the other one had different things too in it. But basically yes, right, additional info
