### ISSUE TITLE
Unity-like icons backlight + gloss

### ISSUE THREAD

**Issue by mrnhmath** [robint99/mate-dock-applet#113]
Dash to Dock recently released an option to enable icons backlight:
![image](https://user-images.githubusercontent.com/13562431/32149081-b5bc81d4-bce6-11e7-8cb2-6d083ed0793b.png)

Would be cool if it was implemented too in mate-dock-applet, and benefical to Ubuntu MATE's Munity layout.

This is an example showing both backlight and gloss on Unity:
![image](https://user-images.githubusercontent.com/13562431/32149118-259134fa-bce7-11e7-884d-10d046218f40.png)

**Comment by CreamyCookie** [comment]
I'd also love icons with colored backlight. Here's the algorithm Unity uses: 

https://bazaar.launchpad.net/~unity-team/unity/trunk/view/head:/launcher/LauncherIcon.cpp#L279

**Comment by robint99** [comment]
I've just committed some changes which give the dock a Unity look :)

![unity](https://user-images.githubusercontent.com/10033637/48699921-8584a880-ebe2-11e8-8c19-d961f2b700ec.png)

There's also a 'flat' option that doesn't have the 'button' look but still gives running apps the backlight. You can select these in the dock preferences: 

![screenshot at 2018-11-19 08-54-31](https://user-images.githubusercontent.com/10033637/48700153-35f2ac80-ebe3-11e8-9424-4fb44e5dd15d.png)

If you want all this now you'll have to compile the applet from source (instructions are on the main page) or wait for the changes to appear in your distro's repositories. In the meantime, I'll close this issue.

**Comment by CreamyCookie** [comment]
Very cool! Thank you! =)
