### ISSUE TITLE
Icons not disappearing

### ISSUE THREAD

**Issue by CodyRude** [robint99/mate-dock-applet#119]
After updating to the most recent git version that uses the Bamf library, I'm having some trouble with icons not dissappearing when the program closes. It seems to happen randomely. Right clicking on the phantom icon doesn't give me any useful options (just dock preferences). They don't go away until I log out.

Other than this issue the switch to using the Bamf library has been great! It haven't found an application it doesn't find properly.

**Comment by robint99** [comment]
Closing this issue as I believe it's related to #166, which is now fixed. If you still have issues, let me know and I'll take another look.
