### ISSUE TITLE
How do I remove the dock applet icon?

### ISSUE THREAD

**Issue by Shadowblitz16** [robint99/mate-dock-applet#121]
just installed ubuntu mate and I can't seem to figure out how to disable the icon of the dock applet.
is there a way to do this?

**Comment by elcste** [comment]
I've never seen an icon for the dock applet. (Are you sure you don't mean Plank?) Can you post a screenshot?

**Comment by Shadowblitz16** [comment]
I am no longer using ubuntu mate since I broke it trying to install packages
but I mean't the icon you click on to get the properties, I wanted to hide it.

**Comment by robint99** [comment]
Closing this issue as no else has reported this problem and it most likely relates to Plank, not the applet.
