### ISSUE TITLE
problem with mate-dock-applet dependencies

### ISSUE THREAD

**Issue by maravento** [robint99/mate-dock-applet#124]
MATE Desktop Environment 1.16.2
Ubuntu Mate 16.04.3 LTS x64

sudo apt-add-repository ppa:ubuntu-mate-dev/xenial-mate -y
sudo apt-get update
sudo apt-get full-upgrade

after reboot and update again:
The following packages have unmet dependencies:
  mate-dock-applet: Depends: gir1.2-keybinder-0.0 but is not installable

Thanks

**Comment by elcste** [comment]
I'd suggest you post this question at the Ubuntu MATE forum (https://ubuntu-mate.community/), since it's an issue with Ubuntu MATE and PPA packaging, not with the dock applet per se.

**Comment by maravento** [comment]
Solved, but in another way:
mate-dock-applet of the ppa repository: ubuntu-mate-dev (MATE Desktop Environment 1.16.2) comes into conflict with mate-dock-applet original version included in Ubuntu Mate 16.04.4 LTS MATE Desktop Environment). Then the conflicting version of mate-dock-applet is uninstalled
