### ISSUE TITLE
Version 0.83 adds extra space on the right side of the panel.

### ISSUE THREAD

**Issue by josgramaxo** [robint99/mate-dock-applet#126]
On Debian testing after upgrade from 0.81 to 0.83 the dock applet adds extra space on the right side of the panel.
![captura de ecra no 2018-03-07 19-09-45](https://user-images.githubusercontent.com/37156611/37113284-d5328688-223c-11e8-80a8-61781cff40f0.png)

**Comment by robint99** [comment]
Finally got around to looking into this and have fixed it.

![screenshot at 2019-01-21 07-57-33](https://user-images.githubusercontent.com/10033637/51460036-48f43b00-1d52-11e9-8795-2a1dad09f720.png)

There was also a related problem with non-expanded panels where the dock and the panel would both receive mouse clicks, so for example you'd click the dock to launch an app and would also start dragging the panel. I've fixed this too.

Cheers.
