### ISSUE TITLE
 Icon stays highlighted with all windows closed

### ISSUE THREAD

**Issue by elcste** [robint99/mate-dock-applet#130]
If the last window that was closed is a pinned app, the app's icon stays highlighted on dock. This cosmetic issue occurs if desktop icons are disabled.

#### Steps to reproduce the behaviour

0. Disable desktop icons (*MATE Tweak → Desktop → Show Desktop icons* or ` gsettings set org.mate.background show-desktop-icons false`).
1. Pin at least one app (I'll use MATE Terminal).
2. Open MATE Terminal.
3. Close (***edit**: or minimize*) all other windows, if any are open.
4. Close MATE Terminal's window.
5. MATE Terminal's icon has no indicator, but it is still highlighted.

#### MATE general version

1.20.1

#### Package version

mate-dock-applet 0.85-0ubuntu1

#### Linux Distribution

Ubuntu MATE Bionic

#### Link to downstream report of your Distribution

https://bugs.launchpad.net/ubuntu/+source/mate-dock-applet/+bug/1763198

**Comment by robint99** [comment]
I've just committed a fix for this. Thanks for the info!
