### ISSUE TITLE
Dock Preferences dialog issues

### ISSUE THREAD

**Issue by gabdub** [robint99/mate-dock-applet#131]
* The Dock Preferences dialog does not show the Dock size options the first time is opened (you have to close and reopen it to show them). See the images bellow.

* The Dock Preferences dialog does not show an icon in the dock and if you minimize it, it disappears and never shows up again. The dialog is not modal.

I'm running version v0.85 (GTK3) from Ubuntu Mate 18.04 Beta 2 + updates.

![dialog1](https://user-images.githubusercontent.com/11639609/38650604-41fa3e1c-3dd3-11e8-88c2-eaabcb817dcb.png)

![dialog2](https://user-images.githubusercontent.com/11639609/38650618-4c9a3336-3dd3-11e8-8074-d4c2f9eeba7c.png)

**Comment by nschulzke** [comment]
It looks like the bug is actually that the Dock size appears on the second load. The code is set to hide it if nice_sizing is possible, and it does that correctly based on log tests.

**Comment by robint99** [comment]
The way this is supposed to work is that the dock size options should only be visible on older versions of MATE. In other words it shouldn't be there at all in 18.04, so I've just committed a fix to make sure this happens.
