### ISSUE TITLE
Program activation by dragging doesn't work

### ISSUE THREAD

**Issue by gabdub** [robint99/mate-dock-applet#132]
The dock does not activate another running program when dragging a file from caja over the program icon.

I'm running version v0.85 (GTK3) from Ubuntu Mate 18.04 Beta 2 + updates.

I added some calls to `log_it()` and found that in the function **applet_drag_motion** (dock_applet.py line 512) the test `if app is None:` is always false. It seems that **app** is not set to **None** when the drag begins.

**Comment by gabdub** [comment]
![dock-p-crash](https://user-images.githubusercontent.com/11639609/39368498-20cdbb58-4a10-11e8-8a11-cd8da748c76b.png)
If I remove the test, the drag works again.
Now running Ubuntu Mate 18.04 (not beta).

**Comment by nschulzke** [comment]
I think it's actually missing a definition for `app`:

```
    app = the_dock.get_dragee()
```

This is in the `applet_drag_end` function, and adding this line just before the check solves the problem for me.

**Comment by gabdub** [comment]
Yes, I think you are right.

**Comment by robint99** [comment]
Thanks to you both for looking into this. It seems that I accidentally deleted that line of code back in February ... I've put it back and committed the change, so I'll close this issue now.

Cheers.
