### ISSUE TITLE
Quick-menu only available with hovering, not right-click

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#135]
In previous versions of mate-dock-applet, right-clicking a Dock icon showed the icon's quick-menu options (such as "open new window" for browsers). In the newer version, right-clicking an icon shows the menu for the dock itself (preferences and so on), and the quick-menu is only available by hovering and waiting for the quick-menu to appear. This materially slows down activating a quick-menu option such as opening a new browser window.

**Comment by elcste** [comment]
@stuartlangridge You can get the options in the right click menu if you disable the popup (*Dock Preferences* → *Panel Options* tab → *Disable popup...*) Of course this will not help you if you want both, however.

**Comment by stuartlangridge** [comment]
Ah, the reason I don't want to do that is that the popup is attractive, and the right-click menu is a less-attractive standard popup menu :) If the right-click menu were also drawn like the popup, I'd be happy to use it and disable it showing up on left-click (and that would also fix issue #134).

**Comment by robint99** [comment]
Unfortunately there's nothing I can do to alter the appearance of the right-click menu so we're just stuck with it. 

As for the length of time it takes a popup window to appear, I can be a bit more helpful. If you go into the dock preferences and select the Misc tab, you'll see it contains an option allowing you to adjust this.

![screenshot at 2018-05-21 10-20-28](https://user-images.githubusercontent.com/10033637/40300261-ac98c834-5ce0-11e8-9b81-db78cede032d.png)

You can take it down to as low as 0.1 seconds...

Will close this issue now.
