### ISSUE TITLE
Telegram icon not found; shows as generic cogs

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#137]
Previous versions of mate-dock-applet showed the Telegram icon correctly. After upgrading to Ubuntu MATE 18.04, the Telegram dock button is showing a generic "cogs" icon.

**Comment by robint99** [comment]
How did you install Telegram? I've tried versions from the Software Boutique and the Snap Store and both show the correct icon:

![screenshot at 2018-05-10 09-49-03](https://user-images.githubusercontent.com/10033637/39862651-492b9288-543c-11e8-8808-815401ab8975.png)

Admittedly, I've never gone past this first screen because I don't use Telegram and don't want to sign up, so if the icon goes wrong after this point, just let me know...

**Comment by stuartlangridge** [comment]
It's installed by hand in a folder via the download from Telegram themselves. I wouldn't have been surprised if the icon didn't work in that situation (although it should), but it worked under 16.04.

The icon seems to be _present_:

    python3 -c "import gi;gi.require_version('Gtk', '3.0');from gi.repository import Gio,Gtk; telegram=Gio.DesktopAppInfo.new('telegramdesktop.desktop'); icon=telegram.get_icon();themeicon=Gtk.IconTheme.get_default().choose_icon(icon.get_names(), 512, 0);filename=themeicon.get_filename();print(filename)"
    /home/aquarius/.local/share/icons/telegram.png

so I'm not sure why m-d-a isn't picking it up.

**Comment by robint99** [comment]
It's sorted now. There were a couple of things going on. Firstly, I was using the Papirus icon theme and this includes icons for Telegram whereas the default Ubuntu Mate icon theme doesn't. This explains why I was seeing the proper icon and you weren't. The other problem was that the applet wasn't always picking up icons from other places, e.g ~/.local/share/icons. I've adapted the snippet of code you provided and the Telegram icon is now correct:

![screenshot at 2018-05-10 14-35-25](https://user-images.githubusercontent.com/10033637/39872293-6ea58cda-545f-11e8-80d7-82ee005e4942.png)

I'll commit the changes in a day or two. First, I want to make sure I can't find any other apps with incorrect icons.

Cheers,

Robin

**Comment by robint99** [comment]
I've committed the fix so will close this issue now.
