### ISSUE TITLE
Bringing opened app to 1st plan when holding file on their icon in dock

### ISSUE THREAD

**Issue by marsjaninzmarsa** [robint99/mate-dock-applet#14]
Useful when drag'n'dropping files between maximized/cascaded windows on single display and workspace.

**Comment by robint99** [comment]
Yes, that would be a useful feature and I've added to my to-do list.

**Comment by milankni** [comment]
+1

**Comment by robint99** [comment]
I've been doing some investigation on this - it seems that drag and drop isn't implemented in the Python Gtk2 bindings. Therefore this is going to have to wait until the applet is ported to Gtk3 :(

**Comment by robint99** [comment]
I've implemented this now. You'll need V0.77 of the applet and Gtk3 MATE :)
