### ISSUE TITLE
Certain function keys cause the keyboard listener to stop working

### ISSUE THREAD

**Issue by nschulzke** [robint99/mate-dock-applet#142]
Original report: https://bugs.launchpad.net/ubuntu/+source/mate-dock-applet/+bug/1767451

I've submitted a pull request that fixes this, but then made a few additional changes to my master branch, which I don't necessarily need pulled.

Here's the commit that's needed: https://github.com/robint99/mate-dock-applet/pull/133/commits/94f0b01779b1782150477c768309d453928a6198

Basically, you just need to check if the event has a state before trying to use it. Certain function keys on laptops don't have a state.

**Comment by robint99** [comment]
Just tried this. My laptop (an old Thinkpad T420) had the same problem and this fixes it.

Thanks for spotting the issue and sorting it out :)
