### ISSUE TITLE
Blurry icons

### ISSUE THREAD

**Issue by cazacugmihai** [robint99/mate-dock-applet#144]
Hi,

The dock applet draws blurry icons on my system:

![mate-dock-applet](https://user-images.githubusercontent.com/89212/39695621-e9ae8f30-51f3-11e8-9386-cb32303f4e6c.png)

The quality of the icons doesn't change, no matter what width I set to the panel. On the above picture, the mate-panel width is set to 48 pixels. 

Env:
```
OS: Ubuntu 18.04 LTS x86_64
Resolution: 3840x2160 
DE: MATE 
WM: Metacity (Marco) 
WM Theme: Arc-Darker 
Window manager: Marco (Compton GPU compositor)
Theme: Arc-Darker [GTK2/3] 
Icons: Arc-Icons [GTK2/3] 
GPU: Intel HD Graphics 530 
```

Thanks!

**Comment by robint99** [comment]
I think this is probably a hidpi issue and I've just committed a fix for it. Unfortunately, I don't have a hidpi monitor to test it with, so I don't know for sure that it actually works...

If you'd like to try it for yourself, you'll have to install the very latest version of the applet. Fortunately I've written a Python script to do this for you and you can find it in [here](https://github.com/robint99/misc) one of my other repositories.

Cheers.

**Comment by vkareh** [comment]
@robint99 - your fix does not scale icons, instead it loads a larger icon size, but then it just shrinks it back for rendering in the corresponding drawing area. I've submitted a pull request that loads scaled icons and converts them to a surface - it then uses that surface as the source for the cairo context during the draw phase.
