### ISSUE TITLE
bamf - seems like a dead end choice

### ISSUE THREAD

**Issue by oz123** [robint99/mate-dock-applet#145]
Currently, it seems that bamf development is quite stalled.
It has some dependencies which don't support python3 which is a bit problematic.
Python2 is soon EOL.

specifically, this is a build dependecy of bamf, which seems even more dead then bamf:
https://launchpad.net/gtester2xunit

**Comment by robint99** [comment]
I don't think bamf is going to go away any time soon - development on it is slow but it still gets occasional updates, e.g. a fix was made in February to improve support for snap and flatpak apps. 

For now I'm happy to go on using bamf, and it it does disappear some time in the future I'll look for a replacement then...

Cheers.
