### ISSUE TITLE
Does not work after compiling

### ISSUE THREAD

**Issue by shiarus** [robint99/mate-dock-applet#147]
Here are my prereqs:
gir1.2-wnck-1.0 (gir1.2-wnck-3.0 also installed)
libglib2.0.dev  
python3         (currently v3.5)
python3-pil     (python imaging library, pytho-pil also installed)
python3-scipy   (python-scipy also installed)

Mint mate uses gtk3, so this was my installation procedure:
aclocal
automake --add-missing
autoreconf
./configure --with-gtk3 --prefix=/usr
make
sudo make install

After installing, the applet will not start after adding it to the panel.
Debugging is useless as **$ python3 '/usr/lib/mate-applets/mate-dock-applet/dock_applet.py'** produces no output and exits. returning the terminal to its previous state.

I am attaching a zip container with the .deb file I generated with **sudo checkinstall**.  This will allow you to check how my system compiled from source and possibly see something I don't
[mate-dock-applet-0.85.zip](https://github.com/robint99/mate-dock-applet/files/2043364/mate-dock-applet-0.85.zip)

**Comment by shiarus** [comment]
This may be a duplicate of https://github.com/robint99/mate-dock-applet/issues/118 .  If it is, feel free to close it.

**Comment by shiarus** [comment]
I tried using v0.80, with the fix for https://github.com/robint99/mate-dock-applet/issues/136 and https://github.com/robint99/mate-dock-applet/issues/140.  I had the same thing happen even then, with and without the modified dock.py.  (The only difference is **$ python3 '/usr/lib/mate-applets/mate-dock-applet/dock_applet.py'** complains about the missing window_control module in dock.py before exiting)

**Comment by robint99** [comment]
There are so many differences between V0.80 and 0.85 that applying fixes between is just not going to work. If you want to continue with 0.80, you may need these to install these dependencies too if you haven't already

python3-xlib
Bamf (bamfdaemon, libbamf and gir1.2-bamf)

If you run the applet from a terminal and it immediately exits, this usually means that applet is already running. What you have to do is kill any existing dock_applet.py process and re-run the applet.

For the past couple of days I've been looking into creating a PPA for the applet so that Ubuntu/Mint/Debian users will always be able to get hold of the latest development version of the applet without having to compile it for themselves. I'm hoping to have this set up within the next week or so, so it may be best for you to wait for that...

**Comment by shiarus** [comment]
libbamf does not exist is in ubuntu or mint repositories.  The rest were installed.

**Comment by shiarus** [comment]
You don't need to worry about a ppa tight away, though maintaining one is a good idea to prevent some of these situations from occurring again.  Once Mint updates so its base is Ubuntu Bionic, they will be using mate-dock-applet (0.85-1) in their universe repository.  See: https://packages.ubuntu.com/bionic/mate-dock-applet

I also have 2 suggestions to help you out:
    1)  In the interest of completeness of you source package, the web page above has all of the 
 current dependencies required for the package to work on Ubuntu-Distributions.  It would be helpful to add that full list into your INSTALL file concerning Ubuntu and Ubuntu-based distributions.  (It may also be worth mentioning that this list looks like it may be Debian compatible, though I do not know where Debian stands with its current release cycle)
    2)  Providing a snap package allow users to pull in dependencies without affecting the rest of their system, this also allows you to provide a Distribution-agnostic solution which all Distributions that support snaps will be able to use.  This may be easier to provide and maintain rather than distribution-specific PPA's, but some distributions do not include snaps in their default install yet.

**Comment by shiarus** [comment]
Snap packages feature auto-update, though I here it is heavy-handed on the developer side of things.  Flatpack is seeing adoption too, with similar benefits.

**Comment by elcste** [comment]
> libbamf does not exist is in ubuntu or mint repositories.

[`libbamf3-2`](https://packages.ubuntu.com/search?keywords=libbamf&searchon=names&suite=all&section=all) (Maybe you'll need the `libbamf3-dev` package too.)

**Comment by shiarus** [comment]
I just checked, and I have libbamf3-2 installed, so it would have been there during my compiling.  I will install the dev package and let you know if that makes any difference.

**Comment by robint99** [comment]
For Ubuntu and Linux Mint I've written a makeshift program to automate the downloading and compiling of the applet, and as part of this it installs any missing dependencies. I've tested it on Ubuntu 16.04 and 18.04 (17.10 will probably work too but I havent' tested it) and Mint 18.3. On Ubuntu you get the very latest applet code from git. On Mint you get V0.80... Hopefully this might be of some use to you. 

If you want to give it a try you can get it from [this link](https://raw.githubusercontent.com/robint99/misc/master/da_installer.py) (right click and do 'save as'). To run it, open up a terminal, cd to the directory where you save the file and do `python3 da_installer.py`

**Comment by shiarus** [comment]
Installed with your script.  The same error as before, mate-panel complains and I can either delete dockbar or ignore the error.  However, I found out that if I run $ python3 '/usr/lib/mate-applets/mate-dock-applet/dock_applet.py' before adding the app to the panel, it works as expected.  Perhaps the app needs to start the python3 command as a service before executing?

**Comment by robint99** [comment]
It's only necessary to specify python3 when starting the applet from a terminal - it should work normally if added from the 'Add to panel' dialog. 

Could you confirm for me - is the dock working correctly now?

Thanks.

**Comment by robint99** [comment]
No response on this for a while so will close this issue now.
