### ISSUE TITLE
Option to set the maximum amount of actions shown

### ISSUE THREAD

**Issue by CreamyCookie** [robint99/mate-dock-applet#153]
The Steam `.desktop` file has a lot of actions:

```desktop
[Desktop Action Store]
Name=Store
Exec=steam steam://store

[Desktop Action Community]
Name=Community
Exec=steam steam://url/SteamIDControlPage

[Desktop Action Library]
Name=Library
Exec=steam steam://open/games

[Desktop Action Servers]
Name=Servers
Exec=steam steam://open/servers

[Desktop Action Screenshots]
Name=Screenshots
Exec=steam steam://open/screenshots

[Desktop Action News]
Name=News
Exec=steam steam://open/news

[Desktop Action Settings]
Name=Settings
Exec=steam steam://open/settings

[Desktop Action BigPicture]
Name=Big Picture
Exec=steam steam://open/bigpicture

[Desktop Action Friends]
Name=Friends
Exec=steam steam://open/friends
```

I'd love to see them all when right clicking.  Currently, only the 4 topmost actions are shown.

**Comment by robint99** [comment]
I've just committed a fix for this. As you noticed, the applet would only display the first 4 actions, but now it displays them all. Screenshots below:

![steam popup](https://user-images.githubusercontent.com/10033637/42308608-fe652084-802d-11e8-9d47-93ad42bc3de0.jpg)
![steam right click](https://user-images.githubusercontent.com/10033637/42308613-012bfcca-802e-11e8-87eb-508a4eab4673.jpg)
