### ISSUE TITLE
Missing menu items to pin/unpin apps in compiled mate-dock-applet v0.86

### ISSUE THREAD

**Issue by ProfP30** [robint99/mate-dock-applet#157]
1.) Freshly installed UBUNTU Gnome Edition 18.04
2.) Then installed the MATE Desktop-Environment
3.) Compiled mate-dock-applet from sources with your [makeshift program script](https://raw.githubusercontent.com/robint99/misc/master/da_installer.py)

Dock panel is now here, but I am missing the option to pin/unpin apps from the menu?

![image](https://user-images.githubusercontent.com/41631425/44030856-613a365c-9f02-11e8-8fe6-75131269ba7e.png)

![image](https://user-images.githubusercontent.com/41631425/44030875-75d33604-9f02-11e8-9bdf-c52a57197220.png)

**Comment by robint99** [comment]
I think this may be the same problem as issue #162. Please see [this reply](https://github.com/robint99/mate-dock-applet/issues/162#issuecomment-416881923) as it may show how to get the pin/unpin options back.

**Comment by ProfP30** [comment]
Yes, this was the case indeed.
Thank you.
Closing this issue.

**Comment by ProfP30** [comment]
the same problem as issue #162
