### ISSUE TITLE
Applet's Background Colour

### ISSUE THREAD

**Issue by rockstorm101** [robint99/mate-dock-applet#161]
Hi I upgraded this applet from version 0.75 to version 0.86, and I use Debian Sid.

I am not able to make it look as it did on version 0.75-1. This is how version 0.75-1 looks like
[1] (applet has the same background as the rest of the panel). With version 0.86-1 and gir1.2-notify-0.7 I am unable to change the dock-applet's background colour to match the rest of the panel [2]. 

 [1] https://imgur.com/a/ePR2wV3 
 [2] https://imgur.com/a/vTCjApt 

Thanks a lot for your time,

**Comment by vkareh** [comment]
@rockstorm101 - what theme are you using? There should be a fix for this already in master, but it's not yet released (v0.86 does not have it). Here it is for reference: https://github.com/robint99/mate-dock-applet/commit/89d6369a3e8c958e3fbfe5d37f8025d6b02c5eee

If you're able to compile this, it'd be awesome to see if it still affects you, as there might still be a few themes that need some love.

**Comment by rockstorm101** [comment]
> @rockstorm101 - what theme are you using? There should be a fix for this already in master, but it's not yet released (v0.86 does not have it). Here it is for reference: 89d6369

Hi @vkareh, thanks for answering this fast. I'm using a custom version of a theme called "Blue-Submarine". 

> If you're able to compile this, it'd be awesome to see if it still affects you, as there might still be a few themes that need some love.

I'm sorry but I lack the resources to compile anything like this right now. Please let me know if I can help in any other way.

**Comment by vkareh** [comment]
@rockstorm101 - you're in luck! Blue-Submarine is the reason I submitted that earlier fix (my wife uses this theme and kept nagging me about it, true story :wink:), so as soon as the next version is tagged and released to Sid you will get the right background color.

**Comment by rockstorm101** [comment]
@vkareh hahaha cool. Thank you very much for taking care of this. I know this is a minor issue in terms of usability but IMHO it severely affects the look and feel and the whole user experience of the MATE DE.

**Comment by rockstorm101** [comment]
@vkareh hahaha cool. Thank you very much for taking care of this. I know this is a minor issue in terms of usability but IMHO it severely affects the look and feel and the whole user experience of the MATE DE.

**Comment by robint99** [comment]
This fix has been included in the latest release of the applet so I will close this issue now.
