### ISSUE TITLE
Missing Pin/Unpin option

### ISSUE THREAD

**Issue by rockstorm101** [robint99/mate-dock-applet#162]
Hi I upgraded this applet from version 0.75 to version 0.86, and I use Debian Sid.

I can't find the option to pin/unpin apps from the dock any more. On version 0.75 (see [1]) an "Unpin" option shows when I right-click the corresponding icon. However now on version 0.86 such option has disappeared [2].

 [1] https://imgur.com/a/w2UfFoR
 [2] https://imgur.com/a/OhNYoLI

Thanks a lot. Please let me know if I can provide any more info in order to debug this.

**Comment by robint99** [comment]
Around the time that 0.75 was released an options was added to allow applet to either display the pin/unpin options in the right click menu or in a popup menu which appears when the mouse hovers over a dock icon. 

![popup](https://user-images.githubusercontent.com/10033637/44777303-2c245480-ab72-11e8-89cf-2db9414ff4e8.png)

The default is to show the popup, but if you want the right click behaviour back there's an option in the applet preferences for this.

![screenshot at 2018-08-29 10-03-12](https://user-images.githubusercontent.com/10033637/44777527-c71d2e80-ab72-11e8-8740-27b7f5b170bb.png)

If you want to keep the popups, there's also an option to specify the delay before they appear.

![screenshot at 2018-08-29 10-06-33](https://user-images.githubusercontent.com/10033637/44777798-65a98f80-ab73-11e8-91ee-dcf2be223abe.png)

Hope this helps :)

**Comment by rockstorm101** [comment]
Thanks a lot @robint99. I didn't know about this pop-up menu. I'm sorry it took me this long to respond.
