### ISSUE TITLE
MATE's Sticky Notes show up in the Dock

### ISSUE THREAD

**Issue by tari01** [robint99/mate-dock-applet#166]
I am testing v0.87 and this what I've found: When there are Sticky Notes displayed on the Desktop, the Dock Applet treats them as regular open windows and shows them with the rest of the apps.

It happens after you open the Preferences dialog for the Sticky Notes.

![sticky notes](https://user-images.githubusercontent.com/9939853/49123918-b6d43700-f2ba-11e8-9758-4d135d41d0eb.jpg)

**Comment by robint99** [comment]
I've just committed a fix for this, and also made sure that the app icon for stickynotes is properly scaled.

**Comment by robint99** [comment]
Oops, forgot to include screenshot - stickynotes is only showing 1 window open, the preferences dialog. Close the dialog and the sitckynotes icon is removed from the dock as you'd expect...

![166](https://user-images.githubusercontent.com/10033637/51591284-87b9fa80-1ee4-11e9-8333-c6936548c5cc.png)
