### ISSUE TITLE
Unpinned applications do not minimize to their own button

### ISSUE THREAD

**Issue by Cpt-Derp** [robint99/mate-dock-applet#167]
Applications that aren't already pinned do not minimize to their button properly, instead minimizing to the left of the applet. Workaround is to move the application button over a spot and minimizing behaves correctly. Tested with Compiz and Marco, ruling out window manager problems.

**Comment by Cpt-Derp** [comment]
The window that doesn't minimize correctly starts to do so if another application opens. The next application in line doesn't minimize correctly.

**Comment by Cpt-Derp** [comment]
Minimizing is updated correctly if the applet is moved along the panel. I have no idea what it's calling in that case. Tried putting set_all_apps_minimise_targets() after the window_added() stuff. No dice.

**Comment by robint99** [comment]
All is working for me now, so this should be fixed for you too :)

**Comment by Cpt-Derp** [comment]
Thank. You.

Confirming fixed by https://github.com/robint99/mate-dock-applet/commit/6e91f3c02f448b8775523691bcb49b5e59504a0a
