### ISSUE TITLE
Wrong desktop file found with symlinks.

### ISSUE THREAD

**Issue by dseomn** [robint99/mate-dock-applet#168]
On my system, `gnome-terminal.desktop` is a symlink to `org.gnome.Terminal.desktop`, and I have `org.gnome.Terminal.desktop` in my pinned apps. When I click on the pinned app, a second icon appears in the dock from `gnome-terminal.desktop`.

**Comment by robint99** [comment]
What distro and dock version are you using? On Ubuntu MATE 18.10 with V0.87 everything works for me - as you can see on the screenshot below I only have one icon even though I have two Gnome Terminals running...

![screenshot at 2019-01-22 09-16-51](https://user-images.githubusercontent.com/10033637/51524652-7f9b8580-1e26-11e9-9a17-83062d9f62a0.png)

If you're using an older version of the applet (earlier than 0.80) this may well be the problem. In V0.80 I completely changed the way in which apps are match to desktop icons.

**Comment by dseomn** [comment]
> I only have one icon even though I have two Gnome Terminals running...

The issue I had was two icons with *one* terminal running.

> If you're using an older version of the applet (earlier than 0.80) this may well be the problem. In V0.80 I completely changed the way in which apps are match to desktop icons.

I noticed the problem on 0.80 of the applet (custom distro). I just tried to reproduce on 0.87 (Debian Testing) and I wasn't able to reproduce it. Oops, sorry for the noise.
