### ISSUE TITLE
Indicator for pinned apps from all / current workspace

### ISSUE THREAD

**Issue by milankni** [robint99/mate-dock-applet#24]
How about adding a preference option for "pinned applications" to deal with multiple workspace setup ("Display pinned apps from all workspaces" vs "Display pinned app only from current workspace").

At the moment, the "dot" indicator is shown for applications from all workspaces.

By the way, there seems to be a small incosistency even in the current behaviour:
= Clicking on icon moves the user to the workspace where the application resides and puts the window in front (correctly).
= However, scrolling with mouse wheel over the app icon traverses through application windows only on the current workspace (if there is none on the current workspace, nothing happens).

**Comment by robint99** [comment]
I've added this preference option in the latest version of the applet, 0.66, just released. One thing to note though, pinned apps will not be hidden unless they're on a different workspace AND they're running. 

I've also looked into the mouse wheel scrolling/workspace problem and this seems to be working now.

Cheers.

**Comment by milankni** [comment]
Thanks for the update.

The wheel scrolling works fine - it switches among open windows and changes workspaces accordingly.


Regarding the "Display pinned apps from all workspaces" vs "... from current workspace" only: I have to appologise that I did not express myself clearly.

What I meant was "Display indicator for windows from all workspaces" vs "Display indicator for windows only from current workspace".

That is, I would like to keep the icon for pinned apps always in the panel, but have a choice whether the indicator is shown only for the windows on the current workspace or for all of them.
Then, if I choose "... on current workspace":
x the switching between windows (via wheel scrolling or chosing from list) should be limited the same way - i.e. for the windows either on the current or all workspaces.
x If a window of a pinned app exists on another workspace, then clicking on the pinned app (without indicator) would start a new instance of the app on the current workspace.

P.S. The current behaviour of the new section "Pinned applications" may stay as is, someone may find it usefull. Just the text for options could change: "Display pinned apps on all workspaces" vs "Display pinned apps unless active on another workspace".

**Comment by robint99** [comment]
Ok, I understand now. What I think I'll do is add an option to choose between only showing indicators/window list items for windows on the current workspace or showing them from all desktops.

As for launching a new instance of the app on the current desktop, this can already be done by holding the shift key when clicking the dock icon :)

I'll add the new option in V0.67.

**Comment by milankni** [comment]
Yes, this sounds like what I asked for. Thanks.
