### ISSUE TITLE
Please use this issue to report apps that the app doesn't recognize or work with.....

### ISSUE THREAD

**Issue by robint99** [robint99/mate-dock-applet#27]
This issue is for reporting apps that the dock doesn't work with.

**Comment by robint99** [comment]
Wine apps don't have the correct icons

**Comment by robint99** [comment]
Steam apps don't have the correct icons

**Comment by NeoTheFox** [comment]
chrome/chromium ups are not showing up, for instance [Hangouts](https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd?hl=en)
![Screenshot](https://i.imgur.com/YFpPPZ0.png)

**Comment by robint99** [comment]
Hi NeoTheFox,

If you go into the dock preferences and select the 'Display an indicator for each open window' option you'll see that when Hangouts is opened it is treated as a Chrome/Chromium window. See below:

![hangouts](https://cloud.githubusercontent.com/assets/10033637/11393948/7d47819e-935a-11e5-84fe-d220c946ecdf.jpg)

In fact, if you have the normal window list applet on another panel and enable window grouping, you'll see that it too groups the chrome/chromium and hangout windows together. 

![hangouts](https://cloud.githubusercontent.com/assets/10033637/11394159/58d8666a-935b-11e5-8677-91b074a1689d.jpg)

So you can see that the dock applet is behaving correctly. However, I'll look into adding code to make dock icons pulse when a new window is opened just to make it more obvious what's happening to the user.

Cheers.

**Comment by NeoTheFox** [comment]
Thanks for the answer, it actually creates .desktop files for the apps in ~/.local/share/applications

**Comment by milankni** [comment]
Hi robint99,

there are no icons for windows created from an existing windowed application.

The original application window is Internet Explorer run by:
$ xfreerdp -u 'User' -p 'pswd' --f --app --plugin rail --data "||IE" -- 10.10.10.61
is recognised as an icon by the dock applet, althoug the icon is wrong (it shows "settings" type of icon, aka "cogweel"). This is not a big deal at the moment, it might well be that the icon is not passed correctly by Windows or xfreerdp.

However, when I run other apps from the original window (it is actually a citrix web app, which shows citrix launchers), the other apps windows are not cought by the dock panel - not even as "sub-windows" of the original application.

Here are the X window properties:

== original RemoteApp run directly by xfreerdp

```
$ xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x44000ee "Citrix XenApp - Logged Off - Internet Explorer"

  Absolute upper-left X:  116
  Absolute upper-left Y:  82
  Relative upper-left X:  116
  Relative upper-left Y:  82
  Width: 1002
  Height: 591
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +116+82  -1442+82  -1442-767  +116-767
  -geometry 752x491+116+82


$ xprop
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 250 by 100
		program specified maximum size: 2572 by 1452
		program specified resize increment: 1 by 1
_NET_WM_ICON_GEOMETRY(CARDINAL) = 717, 1406, 34, 34
XKLAVIER_STATE(INTEGER) = 0, 813113088
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_NAME(UTF8_STRING) = "Citrix XenApp - Logged Off - Internet Explorer"
WM_NAME(STRING) = "Citrix XenApp - Logged Off - Internet Explorer"
_NET_WM_PID(CARDINAL) = 16352
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
WM_CLASS(STRING) = "RAIL", "RAIL:0003007E"
```

== Another Window opened from the RemoteApp
```
$ xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x4400867 "Private (K:) - \\Remote"

  Absolute upper-left X:  242
  Absolute upper-left Y:  807
  Relative upper-left X:  242
  Relative upper-left Y:  807
  Width: 1104
  Height: 570
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +242+807  -1214+807  -1214-63  +242-63
  -geometry 992x543+242-63


$ xprop
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 112 by 27
		program specified maximum size: 2572 by 1452
		program specified resize increment: 1 by 1
XKLAVIER_STATE(INTEGER) = 0, 813113088
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_NAME(UTF8_STRING) = "Private (K:) - \\\\Remote"
WM_NAME(STRING) = "Private (K:) - \\Remote"
_NET_WM_PID(CARDINAL) = 16352
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
WM_CLASS(STRING) = "RAIL", "RAIL:000401B0"
```

When I start as a remote app e.g. the "cmd" and then start various programs (explorer.exe, notepad, ...) then the dock applet recognises all windows as expected.

Is there anything I can help with to identify the problem with citrix apps?

**Comment by milankni** [comment]
P.S. The setup is somewhat complicated because there is no linux Citrix client for connection to the Citrix server. Hence I connect from virtual machine with Windows 7 (KVM-Qemu). The xfreerdp steps in so that I have seamless windows integration into my linux desktop.
I also tried the standard MATE app window applet for the panel and it does not show the "other app window" as well...

**Comment by arxo** [comment]
These application do have the proper icon in the window list, but not in the dock:
- DBGL (DosBox Game Launcher), a Java application
- TeamSpeak 3
- FS-UAE Launcher

**Comment by ekner** [comment]
I guess TeamSpeak is a custom desktop file, because TeamSpeak doesn't come with any real installer.

**Comment by arxo** [comment]
It is, but for other applications (e.g. Xonotic) a custom desktop file works just fine with Dock (ironically, in the case of Xonotic the icon in the window list is wrong this time... ;)

**Comment by ekner** [comment]
Perhaps it would be easier to troubleshoot if you could post the contents of all custom made desktop files.

**Comment by arxo** [comment]
Teamspeak:
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[en_US]=/SOMEWHERE/TeamSpeak3-Client-linux_amd64/styles/classic/logo-128x128.png
Name[en_US]=Teamspeak
Exec=/SOMEWHERE/TeamSpeak3-Client-linux_amd64/ts3client_runscript.sh
Name=Teamspeak
Icon=/SOMEWHERE/TeamSpeak3-Client-linux_amd64/styles/classic/logo-128x128.png

```
Xonotic:

```
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon=/SOMEWHERE/Xonotic/Xonotic.app/Contents/Resources/Xonotic.png
Exec=/SOMEWHERE/Xonotic/xonotic-linux-sdl.sh
Name=Xonotic

```

DBGL:
```
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon=/SOMEWHERE/dbgl/dbgl.png
Exec=/SOMEWHERE/dbgl/dbgl
Comment[en_US]=DoxBox Game Launcher
Comment=DoxBox Game Launcher
Name[en_US]=DBGL
Name=DBGL
```

FS-UAE Launcher (stock Ubuntu MATE)
```
[Desktop Entry]
Name=FS-UAE Launcher
Comment=Launcher for FS-UAE Amiga Emulator
TryExec=fs-uae-launcher
Exec=fs-uae-launcher %f
StartupNotify=true
Terminal=false
Type=Application
Icon=fs-uae-launcher
Categories=System;Emulator;
```

Netbeans (stock Ubuntu MATE)
```
[Desktop Entry]
Name=NetBeans
Comment=Integrated Development Environment
Comment[de]=Integrierte Entwicklungsumgebung
Exec=netbeans
Icon=netbeans
Categories=Development;IDE;Java;
Terminal=false
Type=Application
Keywords=development;Java;IDE;platform;javafx;javase;

```

**Comment by arxo** [comment]
Just upgraded to MATE 1.14.1, including V0.71 of dock - FS UAE Launcher now works properly. :)

**Comment by rrcdm** [comment]
Remote applications using X remote display don't show on dock applications. I'm using Ubuntu Mate 16.04 and when I open an application on another computer using ssh and remote display, mate-dock-applet doesn't show it, even though the window list applet shows it.

**Comment by karas84** [comment]
matplotlib pyplot plots have wrong icon, they are shown with a gear icon instead of:
- a 'sine' icon if launched from python2/3
- ipython icon if launched from ipython2/3

You can reproduce it with:
```
import matplotlib.pyplot as pl
pl.figure()
pl.show()
```
to install matplotlib: `pip install matplotlib`

**Comment by xinomilo** [comment]
tor browser appears in the window list, but not in the dock-applet.
debian sid amd64 - mate 1.16.1

**Comment by filat0ff** [comment]
![30_001](https://cloud.githubusercontent.com/assets/7625639/24501043/891e3d4a-1550-11e7-915e-7f3bef685f70.png)

I have pinned caja application to dock. But when i click on it shows new icon of caja and pinned icon start blinking.

**Comment by tari01** [comment]
I have already filed a [bug report in Launchpad](https://bugs.launchpad.net/ubuntu/+source/mate-dock-applet/+bug/1683230), but here goes an example app:

(Under Ubuntu MATE 16.10  with 0.75 all worked well, 17.04 running 0.77 does not behave properly)

This is the desktop file for [Unity Mail](https://launchpad.net/unity-mail) (I have omitted the translations and descriptions for readability):

**[Desktop Entry]**
Version=1.0
Name=Unity Mail
Icon=unity-mail
Exec=unity-mail-url Home
Type=Application
Categories=Email;Network;
Actions=Clear;Compose;Sent;Change;Inbox;
X-GNOME-UsesNotifications=true

**[Desktop Action Clear]**
Name=Mark all as read
Exec=unity-mail-clear
NotShowIn=Messaging Menu;

**[Desktop Action Compose]**
Name=Compose Mail
Exec=unity-mail-url Compose
NotShowIn=Messaging Menu;

**[Desktop Action Inbox]**
Name=Inbox
Exec=unity-mail-url Inbox
NotShowIn=Messaging Menu;

**[Desktop Action Sent]**
Name=Sent
Exec=unity-mail-url Sent
NotShowIn=Messaging Menu;

**[Desktop Action Change]**
Name=Settings
Exec=unity-mail-settings

**[Desktop Action Inbox]**
Name=Inbox
Exec=unity-mail-url Inbox
NotShowIn=Messaging Menu;

_unity-mail-url_, _unity-mail-settings_ and _unity-mail-clear_ are all Python scripts that use DBUS to communicate with the main application. Only  _unity-mail-settings_ behaves properly: it blinks until it presents a dialogue.

The buggy part:

_unity-mail-url_ either opens the browser or executes a command, depending on the configuration. When clicked, it blinks indefinitely. 

_unity-mail-clear_ only sends a DBUS "message" to the main application. It also blinks forever.

If any of these is i clicked again, another blink timer is started and the pulsing is twice as fast. On third click its even faster, and so on. I can only end this by selecting _unity-mail-settings_, which stops the blinking as soon as the dialogue is shown.

**Comment by Unaccounted4** [comment]
I have the exact same issue as @filat0ff

**Comment by elcste** [comment]
Disks (`gnome-disk-utility`) appears on the dock as "Disk Image Writer". I'm on Ubuntu MATE 17.04 with the latest dock-applet from WebUpd8's PPA, but it also happens with older versions.

**Comment by CodeMouse92** [comment]
Multiple files open in LibreOffice 5.3 do not display correctly. Only ONE icon and indicator light show (although one-indicator-per-window is set), no matter how many are open. First LibreOffice window/file gets the icon, and the other doesn't even appear on the dock.

**Comment by clessley** [comment]
Firefox 57.0a1 (2017-08-08) (64-bit) does not appear in the dock at all. If I create a pinned launcher, it will increasingly blink with every window launch. Using Marco software compositor. The icons are correct in the taskbar and the run dialog.

**Comment by elcste** [comment]
@clessley I'm assuming you are using the Mozilla build of Firefox Nightly, which doesn't include a .desktop file.

This is the best guide I've found for creating one: https://blog.nightly.mozilla.org/2016/09/19/getting-firefox-nightly-to-stick-to-ubuntus-unity-dock/ (I do it a little differently, which I'm happy to share.)

***

With the .desktop file Nightly works normally for me with the dock, with the exception of the first run after Nightly updates itself. For this first run, it will show up as Firefox until I quit and reopen it.

The only time this is a problem is if I quit Nightly after it updates without first restarting, so the next launch it will open as Firefox on the dock. If I've launched it by clicking the Nightly icon, it will keep blinking until I quit and reopen Nightly (or unpin Nightly from the dock).

**Comment by clessley** [comment]
@elcste It showed up on first run as the gearbox icon, then never again. The default firefox's icon also disappeared afterward even after purge, clean, reboot and reinstall. I see Nightly updated again today and things like last pass work now.  I'll try the .desktop file and report back. Its worth the speed increase for a little annoyance. For others, put a window button on the bar in the interim.

**Comment by CodeMouse92** [comment]
Snap applications don't have the correct icons. By way of example, I have my own (omission - coming to the store in September, test installed in the meantime), as well as "ohmygiraffe" (currently available). My own application displays the Python logo, and ohmygiraffe shows, ironically enough, my logo. In both cases, Plank and the menus show the right icon.

**Comment by Isakku** [comment]
Uhm just noticed that after installing Netbeans 8.1 many of the icons and their context menus became Netbeans! It happens with libreoffice, it happens with chromium, and more apps, all of them become "Netbeans" icon, name and context menu! I don't know what the heck Netbeans did but that's the story.

**Comment by alex4321** [comment]
Have problem with Pycharm (maybe same problem with other Inteliji IDE). Sucessfully reproduced with community edition (you can see it in https://www.jetbrains.com/pycharm/download/#section=linux)
Icon not appearing. E.g. I started command :

    user@user-desktop ~/bin/pycharm-2017.2/bin $ ./pycharm.sh

So when IDE succesfully initialized - I can't see their icon:

![screenshot](http://i.imgur.com/hP1F6xf.png)

At screenshot you can see vivaldi/caja/terminal/telegram/skype/slack, but not pycharm.

About mine installation:

- mint 18.2 with mate
- mate-dock-applet installed this way - https://bugs.launchpad.net/linuxmint/+bug/1706994

**Comment by alex4321** [comment]
@Isakku During debugged of mine case I succefully reproduced your bug with netbeans and maked this fork (also, sended pull request): https://github.com/alex4321/mate-dock-applet
Seems like with patched algorythm of *.desktop file mapping - it's gone away

**Comment by clessley** [comment]
@elcste Tried the desktop instructions you shared and it worked when pinning the nightly firefox app to the bar but still nothing in mate-dock. I downloaded the standalone firefox nightly per [http://www.omgubuntu.co.uk/2017/08/download-firefox-57-nightly](http://www.omgubuntu.co.uk/2017/08/download-firefox-57-nightly) and dumped all files into the /opt/firefox folder as directed by [https://blog.nightly.mozilla.org/2016/09/19/getting-firefox-nightly-to-stick-to-ubuntus-unity-dock/](https://blog.nightly.mozilla.org/2016/09/19/getting-firefox-nightly-to-stick-to-ubuntus-unity-dock/). It complained a lot about empty spaces but validated. No dock joy. All other icon locations seem ok.

**Comment by elcste** [comment]
I unpack the archive into `~/bin/firefox-nightly` and create the symlink `~/bin/nightly` → `~/bin/firefox-nightly/firefox`. Here's [my .desktop file](https://gist.github.com/elcste/7beca9eff51d9545a9f56ca67ee0f7d2), which has worked for me.

**Comment by clessley** [comment]
Firefox & Nightly still missing from mate-dock. I tried @elcste file above and it exhibited the same behavior; on the panel but not in the dock. I upgraded to 17.10 thinking it would recreate the standard firefox dock config file but it still exhibits the same behavior. Its just nowhere unless I have a panel with window buttons.

**Comment by clessley** [comment]
I got firefox to come back to the dock after I purged and manually removed all nightly installs and deleted all .desktop config files I could find with that name. The active firefox .desktop file couldn't be deleted (I had it open and running) but one duplicate (interestingly named nightly) did. Next reboot firefox is back in the mate-dock upon start.

**Comment by elcste** [comment]
[Reported on Launchpad](https://bugs.launchpad.net/ubuntu/+source/mate-dock-applet/+bug/1730015):

> The Mutiny docks opens Libre Office files as HP Fax Documents. The HP icon is shown in the dock. This does not happen in other layouts, only in Mutiny.

**Comment by clessley** [comment]
Any fix for libreoffice items that are opened directly showing just the gears icon in the dock? I can open a Writer or Calc doc from inside LibreOffice it'll show the correct icon. If I open the writer/calc doc directly from the desktop "on with" I get the gears icon in Mate Dock.

**Comment by fugo** [comment]
Icon from Palemoon 27.6.0 didn't show up correctly ( issue #112 )
I use Mate 1.15.0 with Mint 18.2 and Dock 0.79

**Comment by robint99** [comment]
I've just made some major changes to the way the applet matches apps. Rather than trying to work it all out for itself it now uses the Bamf library (https://launchpad.net/bamf). This is the same library that Unity and Plank use for app matching, so the dock applet should now be as good as they are in doing this.

The code is already committed here on github, so if you're feeling brave you can try it yourself. If you do this though you'll need to install the bamf library (there may also be a bamf daemon package which also  needs to be installed) from your distro's package manager. This is pre-installed on Ubuntu Mate, so no worries there...

I've got some more changes to make, so I'll combine all the new stuff into a new version of to be released in a few weeks time. In the meantime I'm going to close this issue because it is no longer relevant.

Cheers.
