### ISSUE TITLE
indefinite icon blinking

### ISSUE THREAD

**Issue by akabdog** [robint99/mate-dock-applet#32]
Hello there, thanks for a great applet!

I have a few chrome windows open, perhaps one of them received a notification of some kind. Now the icon is blinking and I can't figure out how to stop it from blinking. I've cycled through all windows and tabs, nothing seems to work.

Here is a list of chrome windows I have open (some of these are chrome applets):
Evernote
Netflix
Plex
Hangouts

I'm running ubuntu 14.04, I've attached a picture with the my versions and panel
![image](https://cloud.githubusercontent.com/assets/8573988/12042846/c73d1130-ae33-11e5-85e0-b586b4cd2e56.png)

**Comment by robint99** [comment]
I've tried to reproduce this but haven't not had any luck so far. I'll keep trying, but in the meantime I have a question - if you have a standard window list applet running as well, does the Chrome window in that keep flashing, or is it just the icon in the dock that flashes?

Cheers

**Comment by akabdog** [comment]
Thanks for looking into it.
The chrome window in the standard window list applet does not flash, just the icon in the dock.

Unfortunately, I upgraded to a 4k monitor and MATE became practically un-usuable, it customizes so well on most things but isn't ready for 4k at all. 
Now that I'm not running MATE, I won't be able to debug this further, feel free to close if you can't replicate.

Thanks much.

**Comment by robint99** [comment]
I'll keep this open and carry on trying to replicate. Thanks for the info.

**Comment by robint99** [comment]
Haven't been able to reproduce this, so will close the issue.
