### ISSUE TITLE
Drag & drop Application Launcher creation

### ISSUE THREAD

**Issue by sshtmc** [robint99/mate-dock-applet#44]
Hi,

just wanted to suggest support for drag & drop creation of application launchers.

Pinning an app does already work to an extent (if the application does not fork in a strange way, as some apps do), and manual creation of application launchers also works as expected.

What would be cool is if the dock-applet could accept drag&drop of other .desktop application launchers and handle them to create dock-applet specific launchers.

BTW, thanks for this awesome plugin!

**Comment by robint99** [comment]
Hi, 

Drag & drop is on my to-do list, but unfortunately it's not supported by the Python interface to Gtk2 that the applet uses. Because of this I probably won't be able to add d&d until I make a Gtk3 version of the applet (d&d is working in Gtk3 python apps I believe) and I should hopefully be doing this quite soon. You'll have to be running a Gtk3 version of Mate to use it though....

Btw, when all this eventually arrives what I'm planning to add, apart from drag and drop creation of launchers, is drag and drop rearranging of the launchers so I can get rid of the current clunky way of doing it.

Glad you like the applet!

Cheers

**Comment by sshtmc** [comment]
I'll have to stick to the Gtk2 version of Mate that comes with Ubuntu 14.04 for the time being (at least 1 more year) so I won't be able to use the new DnD functionality, unfortunately.

I haven't done any DnD app, so I can't say anything new, but I did a quick google search and a few examples with DnD and Gtk2 popped up. I suppose they can't help you (otherwise you wouldn't say that we have to wait until Gtk3 support comes), but I'll share the links anyway in case they might be of use:

http://www.pygtk.org/pygtk2tutorial/sec-DNDMethods.html
http://stackoverflow.com/questions/1219863/python-gtk-drag-and-drop-get-url

Cheers!

**Comment by robint99** [comment]
Yeah, I've seen those links before. They both refer to Pygtk which is the old way of using Gtk. Mate (and the applet) now uses PyGI which is the one that doesn't do d&d.

Thanks for taking the time to look though :)

**Comment by DavideRossi** [comment]
I do not know if that is related but a issue I have with the applet is that I cannot drag something into an icon in the dock to have the corresponding application raise to the foreground. So, say, I cannot drag a file from the file manager to the thunderbird icon on the dock to have my composition window pop up so that I can drag there the file as an attachment.
I tried to understand if this behavior is available using gtk3, I'm on Mint 18.1 which is a gtk2/3 hybrid, but when I try to add the dock to a panel I get the error listed below (I compiled from sources and compilation was flawless).

```
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]: Traceback (most recent call last):
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:   File "/usr/lib/python3/dist-packages/gi/importer.py", line 138, in load_module
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:     introspection_module = get_introspection_module(namespace)
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:   File "/usr/lib/python3/dist-packages/gi/module.py", line 275, in get_introspection_module
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:     module = IntrospectionModule(namespace, version)
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:   File "/usr/lib/python3/dist-packages/gi/module.py", line 122, in __init__
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:     repository.require(namespace, version)
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]: gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]: During handling of the above exception, another exception occurred:
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]: Traceback (most recent call last):
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:   File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 54, in <module>
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:     from gi.repository import MatePanelApplet
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:   File "/usr/lib/python3/dist-packages/gi/importer.py", line 140, in load_module
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]:     raise ImportError(e)
Mar 17 23:15:25 XPS13 org.mate.panel.applet.DockAppletFactory[1583]: ImportError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

```

**Comment by robint99** [comment]
Drag and drop launcher creation (from menu applets) is now supported, as of V0.77 of the applet, which I've just released. Therefore I'll close this issue.

@DavideRossi did you include the --with-gtk3 switch when you ran ./configure ? It looks as though the applet has been compiled with gtk2 support. Also, the new version of the applet allows you to drag and drop data between applications in the way you describe :)

**Comment by DavideRossi** [comment]
Yes, this is with the --with-gtk3 switch.
No errors or warnings during build but no way to have it working.
This is a real shame, that means that users with the latest Linux Mint cannot use the applet.
If there's something I can do to help just let me know...

**Comment by robint99** [comment]
I installed Mint in a virtual machine and it seems that they're still using Gtk2 versions of Mate. Therefore when you run .configure you don't need the --with-gtk3 switch. That should get the applet running, but unfortunately drag and drop doesn't work in python/gtk2 so you won't get any of that goodness...

**Comment by DavideRossi** [comment]
That's from Mint's what's new for 18.1:
```
In MATE 1.16, the following components also switched to GTK3:

The notification daemon
The MATE policykit library
The session manager
The MATE terminal
```
So it looks like this is some kind of a hybrid, but I have to admit I have zero knowledge on GTK.
