### ISSUE TITLE
Rename repository from "dock-applet" to "mate-dock-applet"?

### ISSUE THREAD

**Issue by kq01526** [robint99/mate-dock-applet#45]
Hi @robint99 ,

this GitHub repository is called "dock-applet", yet all the packages seem to be called "mate-dock-applet".

Why not rename the repository from "dock-applet" to "mate-dock-applet" as well to better reflect this?

Renaming the repository should be harmless according to:

https://github.com/blog/1508-repository-redirects-are-here
https://help.github.com/articles/renaming-a-repository/

:wink:

**Comment by robint99** [comment]
Hi,

I expect I will get around to doing this at some point, perhaps after
Ubuntu Mate 16.04 has been released and I've fixed all the new bugs that
get reported 😉

I've added it to my to-do list though...

Cheers,

Robin

**Comment by kq01526** [comment]
>  @robint99 wrote:
> 
> perhaps after Ubuntu Mate 16.04 has been released

It has been released now.

>  @robint99 wrote:
> 
> and I've fixed all the new bugs that get reported :wink:

Why would you wanna wait? It will not break any links, see:

https://github.com/blog/1508-repository-redirects-are-here
https://help.github.com/articles/renaming-a-repository/

:wink:

Regards

**Comment by robint99** [comment]
Done. Thanks for reminding me, I'd forgotten all about it!
