### ISSUE TITLE
14.04 - doesnt work

### ISSUE THREAD

**Issue by marksev1** [robint99/mate-dock-applet#47]
What could be the problem that it doesnt work for me on Ubuntu Mate 14.04? How could i debug?

**Comment by marksev1** [comment]
Any feedback?

**Comment by robint99** [comment]
To debug, run this command in a terminal:

`python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py`

You'll see a long warning message about python and gtk2, this is ok and expected. Anything else will give you an idea of what is going wrong ....

If you've installed the applet from the webupd8 ppa, it might be an idea to make sure that the python3-pil and python3-scipy packages are installed. Recent versions of the applet require them and I'm not sure if the ppa has been updated to include them as dependencies....

Hope this helps...

**Comment by marksev1** [comment]
Yep it was those dependencies, thanks :).

**Comment by marksev1** [comment]
See above

**Comment by robint99** [comment]
This is a problem I solved several versions of the applet ago and having looked at the PPA, it seems that the applet it contains is still at V0.67 whilst the current version is 0.71. I've emailed webupd8 to see if they plan to update the PPA and will let you know when I get a reply. 

In the meantime, all I can suggest is that to get rid of the error you're having is to manually install the latest version of the applet....

**Comment by marksev1** [comment]
Is it compatible with checkinstall? So I can uninstall it with ease.

**Comment by robint99** [comment]
Afaik its not compatible with checkinstall but uninstallation is easy - you
need to keep the directory which has the installation files and then at any
point you can run sudo make uninstall .....

**Comment by marksev1** [comment]
oh cool :) thanks.

**Comment by marksev1** [comment]
Seems to work now. Thanks! Where can I find some docs/tutorial how I should go about using this?
