### ISSUE TITLE
Please add Windows style multiple windows open indicator style

### ISSUE THREAD

**Issue by kq01526** [robint99/mate-dock-applet#50]
Hi @robint99 ,

when an app has a window (or several windows) open, mate-dock-applet indicates that with a dot (or several dots for several windows) on the launcher button app icon.

Windows 7 / 8 / 10 is doing this a little bit different. It doesn't use dots. Instead it kinda stacks the launcher button, see following screenshots for example:

**Windows 7:**
![Image](https://i-msdn.sec.s-msft.com/dynimg/IC420541.png)
[Source](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378460%28v=vs.85%29.aspx#thumbnails)

**Windows 10:**
![Image](http://i.stack.imgur.com/Zg3EK.png)
[Source](http://superuser.com/questions/958690/how-to-make-windows-10-taskbar-thumbnail-previews-bigger)

I like that stacking style and a lot of users coming from Windows are used to it.

Any chance you could add the stacking style to mate-dock-applet as well?

It would be much appreciated.

Regards

**Comment by robint99** [comment]
This has also been added to my todo list, but again it will have to wait until after Gtk3 support is done...

Cheers,

Robin

**Comment by rik-shaw** [comment]
Wondering if there is any more discussion of this now that Mate 1.18 is fully to GTK3?  I think that some richer features in a dock applet would be necessary to meet the expectations of those coming from other environments that may expect richer features (but of course with the window preview effects not enabled then those on lower power machines would not be negatively affected).

**Comment by robint99** [comment]
I've just released a new version of the applet with a Windows 10 type of indicator. As for the window previews, the applet can already do that but it requires that Compiz is used as the window managers.,,
