### ISSUE TITLE
Show Launcher item menus in "Unity style"

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#52]
Unity shows the actions menu for a Launcher item in an attractive style:

![image](https://cloud.githubusercontent.com/assets/4356350/15893659/112f0324-2d79-11e6-95b6-a3b14eb315de.png)

whereas Mutiny shows these as "conventional" Gtk menus, which don't look as nice. Is it possible to copy this menu style? (This may want to be optional, if there are people who prefer the conventional menu style, of course.)

**Comment by robint99** [comment]
The Gtk menu that displays the action menu is the one provided by the MATE panel (the applet just adds its own items to it) so unfortunately there's nothing I can do about the styling of it. However, I've been wanting to get rid of the clutter from this menu for a long time. However what I can at least do is move the options for new windows etc. out of this menu and into the active window list re-done window list (#53) where they'll be displayed in a prettier way.

**Comment by Isakku** [comment]
If you ask me I would like it the way it's requested here: #50

**Comment by robint99** [comment]
As with V0.80 of the applet shaped windows are now supported, so will now close this issue...

![al shaped](https://user-images.githubusercontent.com/10033637/31933767-f92d9d70-b8a1-11e7-889d-15fed26a130a.png)

Note that this requires Gtk3 and python gobject bindings 3.26 or greater.
