### ISSUE TITLE
Active window list is unattractive

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#53]
The active window popup list shown when mousing over a Mutiny Launcher item is rather unattractive, which is disappointing when compared with the rest of mate-dock-applet. Perhaps it could be changed to be prettier?

![image](https://cloud.githubusercontent.com/assets/4356350/15893732/7f1a754e-2d79-11e6-9a76-676fe434c4ff.png)

**Comment by robint99** [comment]
I totally agree that this could use a major makeover.  The Unity style you mention in #52 looks quite nice so that's the sort of thing I'll be aiming to implement. I've got to finish adding gtk3 support first, but once that's out of the way I'll take a look at it...

**Comment by Isakku** [comment]
If you ask me I would like it the way it's requested here: #50

**Comment by robint99** [comment]
With V0.80 of the applet active window lists now look much nicer, so will close this issue.

![wl_shaped](https://user-images.githubusercontent.com/10033637/31933968-92a2813c-b8a2-11e7-8688-5f94372f8293.png)
