### ISSUE TITLE
Misplaced open window menu when using 2 docks

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/mate-dock-applet#56]
Since version 0.72 the hover menu which shows opened windows is misplaced on the second dock applet (right screen). I use 2 panels (each on every monitor) and both have the dock applet.

This worked fine till version 0.71.

mate-panel V1.12.2 (GTK2)
Linux Mint 17.3
Nvidia graphics card with proprietary driver 364.19
Screenshot: https://i.imgur.com/XI4JlUh.png

**Comment by robint99** [comment]
I've just tried this and it seems that the latest changes I've made to window list have fixed it. If you want to give it a try, just grab the latest version of the code...

**Comment by NoXPhasma** [comment]
Yep, with the latest version this issue is fixed, thanks.
