### ISSUE TITLE
Adding a "maximixe" button

### ISSUE THREAD

**Issue by Gnalldo** [robint99/mate-dock-applet#57]
Currently in the Mutiny layout there's a bug where when an application is maximixed there is no way to return it to windowed mode. It seems like the button would fit perfectly beside the close button. This could also make it possible to basically eliminate window borders for smaller monitors.

**Comment by robint99** [comment]
Do you have maxmised windows set to be undecorated? See [here](https://ubuntu-mate.community/t/maximize-minimize-and-close-buttons-dont-appear-on-maximized-window/7291) for more details....

**Comment by Phantom9X** [comment]
The problem only happens because in the Mutiny layout another applet (Top Menu) steals the maximixe button but doesn't give an 'unmaximixe' option so the widow is just stuck in full screen. I was just thinking an 'unmaximixe' button would make sense on the dock.

**Comment by robint99** [comment]
Its certainly possible for me to add an option to unmaxmize button, but digging about in the control centre I found that built into MATE there is actually a keyboard shortcut for toggling a window's maximized state - Alt-F10.  I've tried it with undecorated windows and it works, so it should solve your problem and let you get the most out of your screen space :)

I'll close this bug for now, but if you really do want this sort of feature in the applet, reopen the bug  and I'll consider adding it.

Cheers,
