### ISSUE TITLE
Opening new instance of applications

### ISSUE THREAD

**Issue by gmengass** [robint99/mate-dock-applet#58]
system:
mint 18 sarah x64
mate 1.14.1 
Dock V0.70 installed but when i run apt-get install mate-dock-applet says it is the latest version even though V0.72 is the latest?

Issue:
It is not possible to open a new instance on an already opened docked app for example caja or terminal. However some apps like firefox it is possible to open new window.

**Comment by robint99** [comment]
I presume you installed the applet from the PPA. This is maintained by the folks at webupd8.org and they are the ones who are responsible for including the latest version of the applet. However, I believe they updated it in the last day or two, so you should now be able to get V0.73 of the applet.

To open a new instance of a running app, all you have to is hold down either the <shift> or <Ctrl> key and click the dock icon. Also, some apps (like Firefox or Chrome) have actions for e.g. opening a new window, or a new private window, and with V0.73 these options now appear in the app's pop up window list.

Hope this helps...
