### ISSUE TITLE
Launchers that set environment variables don't work

### ISSUE THREAD

**Issue by karas84** [robint99/mate-dock-applet#66]
As stated in the title, if a launcher sets an environment variable, as shown [here](https://help.ubuntu.com/community/EnvironmentVariables#Launching_desktop_application_with_an_environment_variable), the application is not launched and nothing happens.

**Comment by robint99** [comment]
I've just committed a fix for this, and the application will now launch with the variable set correctly. If you want to try it out you'll have to install the applet from source. If not, you'll need to wait for your distro of choice to package it up and release it.

Cheers
