### ISSUE TITLE
0.73 + Yakkety A1 - hover context behaviour.

### ISSUE THREAD

**Issue by helamsirrine** [robint99/mate-dock-applet#67]
After upgrading to mate-dock-applet 0.73 today I have figured out an odd behaviour with the gtk3 panel that I have noticed ever since installing Yakkety Alpha 1. Observe the pictures. Dock hover context works perfectly when the panel is expanded, Mutiny style. The second screenshot was actually hard to capture because when the panel is not expanded the hover context pops up where it would if the panel were full screen height and quickly disappears. I would guess that this is a problem with mate-panel since I have noticed other issues with panel behaviours on Yakkety.﻿
![screenshot at 2016-07-26 11-34-10](https://cloud.githubusercontent.com/assets/13259436/17152566/ebb7a462-533d-11e6-999a-7d40c5d8b420.png)
![screenshot at 2016-07-26 11-36-47](https://cloud.githubusercontent.com/assets/13259436/17152565/ebb75db8-533d-11e6-911a-06aecc72a988.png)

**Comment by robint99** [comment]
Thanks for info, will take a look at fixing this...

**Comment by robint99** [comment]
I've just committed a fix for this. If you want it straight away you can compile it from source, but I would expect that the fix will find its way into Yakkety before too long...

Cheers.
