### ISSUE TITLE
Adding the applet to panel does nothing

### ISSUE THREAD

**Issue by igorsantos07** [robint99/mate-dock-applet#68]
I'm using a fresh install of Mint 18, with an old home folder. Just installed this really amazing applet but... it doesn't work?
Adding it to the panel does nothing, although on some tests I did notice other applets being moved by some pixels upon "adding" this one.

Is it possible to debug this in some way? Run in terminal, see output, logs, or something similar?

**Comment by robint99** [comment]
You can debug this - just open a terminal and do
`python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py`

If you try adding the applet to the panel you'll get a long message about using Gtk2 with Python which can be ignored. Anything following this will be the actual error. 

If you need any more help to track the problem down and get the applet working, just let me know...
