### ISSUE TITLE
Wishlist: Support Unity-style progress bars

### ISSUE THREAD

**Issue by elcste** [robint99/mate-dock-applet#69]
_Wishlist preface: This is a suggestion only, not a demand._

This [recent post](http://www.omgubuntu.co.uk/2016/08/firefox-unity-download-progress-bar-addon) reminded me about [Unity's progress bars](https://wiki.ubuntu.com/Unity/LauncherAPI). I remember seeing them with the Software Updater and believe Chrome also supports them. It would be a great feature for the MATE dock.

**Comment by robint99** [comment]
The applet now supports this, see below :)

![dock counter and progress bar](https://cloud.githubusercontent.com/assets/10033637/17849301/1c1cc9a8-6850-11e6-93a1-4082d5c8aac6.png)

The code is already committed, so if you're feeling brave you can get this new feature by compiling from source. If not, and presuming you're using Ubuntu MATE, you'll probably have to wait until 16.10 is released to get your hands on it.

Cheers, and thanks for the suggestion!

**Comment by elcste** [comment]
Amazing, thanks! I compiled it in my yakkety VM and voilà:

![untitled](https://cloud.githubusercontent.com/assets/915687/17874854/e40fdb38-6893-11e6-96c5-91cfe1a0bac4.png)

**Comment by kajzersoze** [comment]
Is libunity the only dependency and does this work outside of Ubuntu ?
I tried it on Gentoo and it doesn't work.

**Comment by robint99** [comment]
It does work outside of Ubuntu - I tried it on OpenSuse and had no problem. Firefox needs [this](https://addons.mozilla.org/en-US/firefox/addon/unityfox-revived/) extension for it work though, so if you don't already have it, installing it would definitely help.
