### ISSUE TITLE
Multi monitor | Menu should align on monitor edge instead open always centered

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/mate-dock-applet#71]
When I bring up the menu of the dock near the edge between the 2 monitors, it goes over to the second monitor on the left. This is because the menu always opens in the middle under/over the icon and makes it hard to read the text, due to the monitor borders. Instead it should align on the monitor edge if there is no space to place it centered.

![unbenannt](https://cloud.githubusercontent.com/assets/7719590/17661933/7b1687d2-62e2-11e6-8046-179f9ba97c54.png)

Linux Mint 18 Sarah
Mate-panel 1.14.0
dock-applet 0.73 (Gtk2)

**Comment by robint99** [comment]
I've just committed a fix for this, and window lists now appear properly aligned on the correct monitor.

Cheers.

**Comment by NoXPhasma** [comment]
Hmm, something is broken with this patch. For me the Menu now appears on the top left of my left monitor on top of the panel. No matter which dock I use or which I con I hover. And it doesn't fade away, it keeps there and the next hover menu appears on top of it.

![unbenannt](https://cloud.githubusercontent.com/assets/7719590/18230397/0301430a-729a-11e6-87cc-d386454f31e8.png)

This happens with Marco and Compiz.

**Comment by robint99** [comment]
Ooops. I tested this on Gtk3 Mate and forgot to see if it also worked on Gtk2...

Anyway, it's working on both Gtk3 and Gtk2 now, so you can give it another try.

**Comment by NoXPhasma** [comment]
Not exactly how it should work actually. The dock on my left monitor opens the menu now on the left edge of the right monitor. And the menu of the dock on the right monitor opens it on the right side of the left monitor. Also the menu closes itself after a second, probably because the mouse can't hover on it, because it's too far away.

![hover_left](https://cloud.githubusercontent.com/assets/7719590/18231430/e9ea6b88-72b9-11e6-8db5-561a55ede3b4.png)
![hover_right](https://cloud.githubusercontent.com/assets/7719590/18231431/e9eb3b76-72b9-11e6-8363-9da7775b4d89.png)

**Comment by robint99** [comment]
It seems that panel dconf settings are not the best way to find out what monitor the applet it on. I've committed some changes which use a different method and its working for me on both Gtk2 and 3. Hopefully it will work for you too.


Cheers

**Comment by NoXPhasma** [comment]
Yes, now it works perfectly fine, thank you.
