### ISSUE TITLE
Software Updater Ubuntu Mate doesn't appear on dock

### ISSUE THREAD

**Issue by Thomas-N** [robint99/mate-dock-applet#74]
The Software Updater in Ubuntu Mate periodically checks for updates by defeault. When it finds updates, it pops up a window giving you the option to install them. This window starts minimized, to (I guess) not interrupt your current activity.
The problem is: this minimized Software Updater window doesn't appear on the dock. I only know it's there at all when I alt-tab into it. If you use only the dock to switch between windows instead of alt-tab, you'd never know it was there (and as a result, would never update, potentially leading to security issues).

Edit: This happens using Ubuntu Mate 16.04.1

**Comment by robint99** [comment]
I have two 16.04 setups and this is working fine for me. I can think of one possible explanation for this though. Are you using multiple workspaces? If the updater is somehow popping up on a different workspace to the one you're using and the dock has the 'display unpinned apps only from current workspace' option set, then it won't appear in the dock. To get it into the dock you'd have to alt-tab to make the updater active, and this would then switch workspace and the updater icon would appear...

**Comment by Thomas-N** [comment]
I've set my number of workspaces to 1 for now, to test if this was the problem. I'll report back when Software Updater notifies me again.

**Comment by Thomas-N** [comment]
It was indeed a workspaces issue. When the dock was set to "Display unpinned apps only from current workspace", the Software Updater didn't appear, even when the number of workspaces was set to 1. After changing to "Display unpinned apps from all workspaces", Software Updater appeared normally.

I now think the bug (if there is one) is not with anything the dock applet does, but with the way Software Updater pops up. I'll repost the issue somewhere else.
