### ISSUE TITLE
Compiz window preview overlaping the dock window selection.

### ISSUE THREAD

**Issue by IKRadulov** [robint99/mate-dock-applet#76]
As the name says , when I turn on compiz window prevew plugin it overlaps with the docks window selection . Is a option gonna be made to show the dock list in right click menu?

**Comment by kq01526** [comment]
@IKRadulov , this has already been requested in:

https://github.com/robint99/mate-dock-applet/issues/49

**Comment by robint99** [comment]
In the new version of the applet just released, the popup behaviour can be disabled so it doesn't interfere with Compiz preview windows. Release notes for V0.75 are [here.](https://github.com/robint99/mate-dock-applet/releases)

Cheers
