### ISSUE TITLE
Windows 10 theme?

### ISSUE THREAD

**Issue by kq01526** [robint99/mate-dock-applet#78]
@robint99 :

Any chance you could add a Windows 10 theme to mate-dock-applet?

The Windows 10 taskbar looks like this:

![Image](http://i.stack.imgur.com/Zg3EK.png)
[Source](http://superuser.com/questions/958690/how-to-make-windows-10-taskbar-thumbnail-previews-bigger)

**Comment by marsjaninzmarsa** [comment]
Semi-duplicate: #50, meta: #53
