### ISSUE TITLE
Merging mate-dock-applet with DockbarX?

### ISSUE THREAD

**Issue by kq01526** [robint99/mate-dock-applet#79]
@robint99 :

Wouldn't it make sense if mate-dock-applet would be merged with [DockbarX](https://github.com/M7S/dockbarx) from @M7S ?

DockbarX and mate-dock-applet seem to have the exact same goals.

So why not collaborate and merge the two projects to one to be able to make better progress?

Also asked the same in the DockbarX repo, see: https://github.com/M7S/dockbarx/issues/35 .

Regards

**Comment by robint99** [comment]
This is not something I would particularly want to be involved with.

Basically my aim with the applet is to provide a simple dock for the MATE panel. However, Dockbarx has a wider scope and wants to be a standalone dock for any desktop, with support for themeing, plugins, and its own type of applets. I'll be honest and say that I'm just too lazy to maintain any of this extra stuff when MATE gives it all to me for free ;-) 

I also have concerns that DockBarX isn't being actively maintained  - the last commit on Github was about five months ago and there's no sign of work being done on a port for Gtk3.

That said, both projects are open source so there's no reason why code can't be shared or copied between the two. In fact, as soon I get the time I'm going to take a look at how DockbarX does its window lists. But sharing snippets of code is about as far as I personally want to take things.

So although I've said no, don't forget that there's nothing to stop some other developer from combining the best of both in a brand new project if that's what they want to do...

Cheers.

**Comment by kq01526** [comment]
> @robint99 wrote:
> the last commit on Github was about five months ago and there's no sign of work being done on a port for Gtk3

That's not true, you are looking at the wrong branch, see:

https://github.com/M7S/dockbarx/commits/pygi-migration

https://github.com/M7S/dockbarx/issues/24#issuecomment-238443095

:stuck_out_tongue_closed_eyes:

**Comment by gsantner** [comment]
"not dead" - are you still sure? Last work on dockbarx was august last year. No response on PRs, issues or anything^^
