### ISSUE TITLE
Customize blinking annoyity level

### ISSUE THREAD

**Issue by wentout** [robint99/mate-dock-applet#88]
Hi,
When some app needs attention, it starts blinking in the bar, and until I check what is going on, it will blink. Please, let me have some sort of config for it, cause my skype just almost always blinks while I'm typing in other window, cause a lot of messages there.
I wish to choose how much blinks, I think about numeric value and indefinite checkbox:
|-------------------------------------------------------------------------------------------------------------------|
| How much blinks on necessary attention [ type_number_here ] 0 means indefinite.    |
|_____________________________________________________________________|

Or, moreover, without any blinking it just can be highlighted, cause continuous blinking is very annoying.

**Comment by tari01** [comment]
I second the motion. In 0.77 buggy blinking is a major showstopper. It would be great if we could disable it somehow.

**Comment by robint99** [comment]
I've just released a new version of the applet which allows you to turn off the blinking and instead just display a '!' on the app icon. Hopefully this will be less distracting :)
