### ISSUE TITLE
feature request: 'no-sticky' pinned apps

### ISSUE THREAD

**Issue by gso** [robint99/mate-dock-applet#89]
Similar to Cairo Dock's `--no-sticky` command line arg. ('don't make the dock appear on all desktops'), but for pinned apps and workspaces, i.e., the app. icon appears only on the workspace it was pinned to.  A 'Pin to workspace <workspace name> applet context menu option below the 'Pin <app.> to the dock' menu item would do it.

The list of apps running would maybe have to add data on the workspace a pinned app. is running in, and whether the app. icon should then be sticky or not across workspaces.

Would be a useful feature for organising work on a workspace per task basis, enabling customising app. launchers for a particular workspace / task to be done.

**Comment by robint99** [comment]
I've just added support for this. There's a new preferences option (see below) which allows pinned apps to only appear in the dock on the workspace where they were pinned. 

![screenshot at 2017-09-03 10-14-13](https://user-images.githubusercontent.com/10033637/30001807-f4277ff0-9090-11e7-80a2-84c9607af086.png)

For now, you'll have to compile the applet from source to get this new feature, but once I get a new release of the applet sorted out it'll work its way out to the various distros....

Cheers.

**Comment by robint99** [comment]
Closing this because the feature is now included in the latest release (V0.80) of the applet.
