### ISSUE TITLE
Need update to gtk3

### ISSUE THREAD

**Issue by blisbell** [robint99/mate-dock-applet#9]
Will this be updated to work with the 1.10 gtk3 version?

**Comment by robint99** [comment]
Yes, at some point it will be but at the moment I don't have any timescales in mind...

Cheers

**Comment by blisbell** [comment]
ok just checking I use Arch Linux with gtk3 an getting a gtk2-3 conflict.

**Comment by kq01526** [comment]
@robint99 Are you planning to update mate-dock-applet to GTK+ 3 anytime soon?

**Comment by robint99** [comment]
There's no definite timescale, but I intend to do it sooner rather than
later 😃

**Comment by iondissonance** [comment]
please, update. ubuntu yakkety with mate 1.14  not working

**Comment by GabMus** [comment]
Sorry to be that guy, but this applet is very nice and the lack of a gtk3 version is pretty sad for an end user. Could you at least give us a time when you can start working on it? Thank you for your hard work btw, you're doing great.

**Comment by robint99** [comment]
I'm already working on it 😃

A Gtk3 version should hopefully be available by the end of next week...

**Comment by robint99** [comment]
Gtk3 support has now been added.
