### ISSUE TITLE
Can't install from source in Linux Mint 18.1

### ISSUE THREAD

**Issue by Isakku** [robint99/mate-dock-applet#90]
Sorry to bother you again but I can't install the applet again!
This time I am running Linux Mint 18.1. So, as usual I, was following the instructions at 
https://github.com/robint99/mate-dock-applet 
I downloaded the code from there using the green "clone or download" button,
then I opened synaptic package manager and searched each one of the items in the "Other distributions" list. So, knowing that Mint Mate 18.1 is GTK3 capable I did this:

    Python3 was already installed
    Python wnck bindings (searched for gir1.2-wnck-3.0 and installed it)
    Python bindings to the keybinder library (searched for gir1.2-keybinder-3.0 and installed it)
    Python Imaging Library (searched for python3-pil and installed it)
    Python 3 Cairo bindings (searched for python3-cairo and installed it)
but oh no
    GLib development files (searched for libglib2.0-dev)

I got this awful error

![can t_install_libglig2](https://cloud.githubusercontent.com/assets/16464336/26317464/0bab218a-3f07-11e7-9583-3d7dbc9bf244.png)

libglib2.0-dev:
  Depends: libglib2.0-0 (=2.48.0-1ubuntu4) but 2.48.1-1~ubuntu16.04.1 is to be installed
 Depends: libglib2.0-bin (= 2.48.0-1ubuntu4)
 Depends: libpcre3-dev but it is not going to be installed
 Depends: zlib1g-dev but it is not going to be installed

Being unable to install libglib2.0-dev, I can't do anything. Yeah, even tried searching for libglib3.0-dev 
installing it and running all the other commands just in case, but as it could be expected it didn't work.
Perhaps the updated version of the instructions should be checked and fixed.

**Comment by robint99** [comment]
I've just installed Mint in a virtual machine, updated it, and have been able to install libglib2.0-dev without any problem. 

All I can suggest is that you try again as the Mint repositories may have been in a buggy state ...

**Comment by Isakku** [comment]
Whatever it was you can close this issue. It works well for me in Linux Mint Mate 18.2. Yet I must mention that I had to compile source code with gtk3 option. Webuptdate package didn't work, perhaps because the new Mate version is gtk3 now.

**Comment by robint99** [comment]
Issue closed, and thanks for your kind comments :)
