### ISSUE TITLE
How to reduce the time to see the windows list popup

### ISSUE THREAD

**Issue by abumalick** [robint99/mate-dock-applet#94]
Hello,
thanks for your work I am using it actively for a year and it is working well.

I have a major issue for my productivity that is really important for me : 
When I hover on an APP it takes 1 second to display the windows list popup.

Do you know how to fix that ? I only want to show the popup with no delay...

I am using linux mint installed with mate desktop.

Thanks

**Comment by abumalick** [comment]
Any help on this @robint99 ?
It is really an important feature for me

**Comment by robint99** [comment]
I've just committed a fix for this. There's a new option on the Misc tab of the preferences dialog where you can specify the delay. Valid values are between 0.1 seconds up to 5 seconds in steps of 0.1 second.

For now, you'll have to compile the applet from source to get this, but the fix will be included aspart of the next release.

Cheers

**Comment by abumalick** [comment]
Thank you very much !
