### ISSUE TITLE
dock_applet.py crashed with NameError in treeview_allocate(): name 'Pango' is not defined

### ISSUE THREAD

**Issue by flexiondotorg** [robint99/mate-dock-applet#95]
Hi,

I'm seeing `mate-dock-applet` crash frequently on Ubuntu MATE 17.04 and 17.10 running 0.77 and 0.78 respectively. The crash has been capture in a bug upstream:

  * https://bugs.launchpad.net/ubuntu/+source/mate-dock-applet/+bug/1676524

**Comment by robint99** [comment]
I committed a fix which is tested and working on 17.04. I've also created a new release so you can have this fix and the <Super> key stuff combined in the new V0.79.

Cheers.
