### ISSUE TITLE
Doesn't work with Mint 18.2

### ISSUE THREAD

**Issue by nlchap0** [robint99/mate-dock-applet#97]
I recently upgraded to Mint 18.2 (Mate) and the dock applet no longer works.  The version available in the repository (v 0.70-1build1) didn't work.  so, I downloaded the latest version from github, then followed the directions to compile and install.  I tried both the gtk2 and gtk3 versions.  Both appeared to compile and install successfully.

When I say "didn't work", I mean that the dock applet does show up in the "Add to Panel" dialog box, but when I click "Add", nothing happens.  This is true for the repository, gtk2 compiled, and gtk3 compiled versions.

I looked in /usr/lib/mate-applets, and I do see a directory named "mate-dock-applet".  Is there some way to add it to the panel from the command line, so I can get debug output on what is causing it to fail?

possibly relevant info:
Linux Mint 18.2 Sonya 64-bit
Kernel Linux 4.4.0-83-generic x86_64
MATE 1.18.0
Thinkpad T460

Cheers,

Nicholas

**Comment by galegovski** [comment]
Same here, I've followed all steps and nothing.
But, after all  those, I opened idle3 and ran the dock.py at mate-dock-applet-master/src.
Well, after that, the dock applet started fine.
I hope it works for you too.
Cheers.

**Comment by nlchap0** [comment]
Aha!  Problem solved.  while I had Xlib installed, I only had the python2 version of Xlib.  Once I installed the python3 version using synaptic, then the dock applet worked fine.

Now to see if I can get my gtk and window themes to work like they used to in 18.1...
