### ISSUE TITLE
Mint 18.2 - no dock on panel

### ISSUE THREAD

**Issue by zhum** [robint99/mate-dock-applet#98]
Installed mate-dock from source, all prerequisites checked. After adding to panel no dock appears.

How can I diagnose the root of problem?

**Comment by NoXPhasma** [comment]
Did you compile it with `--with-gtk3`? Mint 18.2 has Mate 1.18 which uses GTK3.

**Comment by Isakku** [comment]
Compiling with gtk3 option made it work for me in Linux Mint Mate 18.2.

**Comment by robint99** [comment]
Mint 18.2 in indeed GTK3 only, so when compiling from source the --with-gtk3 option is required. I've updated the README to note this...
